# frozen_string_literal: true

require "loofah"

module EnrollMiddleware
  # Insert the rails content nonce into in-page script tags
  # where it doesn't exist, and report the violation as a warning.
  class RailsContentNonceRewrite
    def initialize(app)
      @app = app
    end

    def call(env)
      request = ActionDispatch::Request.new env
      stat, headers, body = @app.call(env)
      nonce = request.content_security_policy_nonce
      resp = ActionDispatch::Response.new(stat, headers, body)
      content_type = Mime::Type.lookup(resp.content_type || Mime[:html])
      return [stat, headers, body] unless content_type&.html?

      doc = nil
      begin
        doc = if body.is_a?(ActionDispatch::Response::RackBody)
                Loofah.document(body.body)
              else
                Loofah.document(body)
              end
      rescue StandardError
        return [stat, headers, body]
      end
      doc.xpath("//script").each do |node|
        nonce_node(node, nonce, :script, request)
      end
      # doc.xpath("//style").each do |node|
      #  nonce_node(node, nonce, :style, request)
      # end
      doc.xpath("//*[@onclick]").each do |node|
        request.logger.tagged("CSPTagMissingNonce") { |tl| tl.warn("Detected inline onclick event handler: #{node['onclick']}") }
      end
      response = ActionDispatch::Response.new(stat, headers, doc.to_s)
      response.to_a
    end

    def nonce_node(node, nonce, kind, ad_request)
      return if node["src"] || node["integrity"] || node["nonce"]
      node["nonce"] = nonce
      ad_request.logger.tagged("CSPTagMissingNonce") { |tl| tl.warn("#{kind} tag is missing a nonce: #{ad_request.original_url}") }
    end
  end
end

Rails.application.config.content_security_policy_nonce_generator = lambda do |request|
  # use the same csp nonce for turbolinks requests
  if request.env['HTTP_TURBOLINKS_REFERRER'].present?
    request.env['HTTP_X_TURBOLINKS_NONCE']
  else
    SecureRandom.base64(16)
  end
end
Rails.application.config.content_security_policy_nonce_directives = %w[script-src]

Rails.application.config.content_security_policy do |policy|
  csp_proto = Rails.env.production? ? :https : :http
  policy.default_src :self, csp_proto
  policy.object_src  :none
  policy.base_uri    :self
  policy.font_src    :self, csp_proto, :data, "*.gstatic.com",  "*.fontawesome.com"
  policy.img_src     :self, csp_proto, :data, "*.google-analytics.com", "*.gstatic.com", "*.googletagmanager.com"
  policy.script_src  :self, csp_proto, "https://tagmanager.google.com", "https://www.googletagmanager.com", "https://apps.usw2.pure.cloud", "*.fontawesome.com", "*.google-analytics.com", "https://js-agent.newrelic.com"
  policy.style_src   :self, csp_proto, "'unsafe-inline'", "https://tagmanager.google.com", "https://www.googletagmanager.com", "https://fonts.googleapis.com", "*.fontawesome.com", "https://*.mypurecloud.com"
  policy.connect_src :self, csp_proto, "https://api.usw2.pure.cloud", "wss://streaming.usw2.pure.cloud", "*.nr-data.net", "wss://webmessaging.usw2.pure.cloud"
  policy.media_src   :self, csp_proto, :data
  policy.frame_src   :self, csp_proto, "https://*.cme.openhbx.org", "https://*.coverme.gov", "https://*.usw2.pure.cloud"
end

Rails.application.config.middleware.insert_after Browser::Middleware, EnrollMiddleware::RailsContentNonceRewrite


if defined?(NewRelic)
  require 'new_relic/rack/browser_monitoring'

  module NewRelic
    module Rack
      # Override the implementation for nonce inclusion.
      # This is currently a bug in our NewRelic 9.7.1 gem version -
      # if you upgrade or change the gem version, you **WILL** need to change
      # this code.
      # rubocop:disable Metrics/BlockNesting
      class BrowserMonitoring < AgentMiddleware
        def traced_call(env)
          result = @app.call(env)
          (status, headers, response) = result

          js_to_inject = NewRelic::Agent.browser_timing_header(nonce(env))
          if (js_to_inject != NewRelic::EMPTY_STR) && should_instrument?(env, status, headers)
            response_string = autoinstrument_source(response, js_to_inject)
            if headers.key?(CONTENT_LENGTH)
              content_length = response_string ? response_string.bytesize : 0
              headers[CONTENT_LENGTH] = content_length.to_s
            end

            env[ALREADY_INSTRUMENTED_KEY] = true
            if response_string
              response = ::Rack::Response.new(response_string, status, headers)
              response.finish
            else
              result
            end
          else
            result
          end
        end

        # Supply the nonce based on our hack.  We can't trust newrelic to
        # auto-detect it when it's generated by our middleware.
        def nonce(env)
          request = ActionDispatch::Request.new env
          request.content_security_policy_nonce
        end
      end
      # rubocop:enable Metrics/BlockNesting
    end
  end
end