---
registry:
  - namespace:
    - :enroll_app
    - :aca_individual_market
    features:
      - key: :qhp_application
        item: :qhp_application
        is_enabled: <%= ENV['QHP_APPLICATION_IS_ENABLED'] || false %>
