# frozen_string_literal: true

module Operations
  module HbxEnrollments
    # OnSave operation that handles enrollment processing after save events.
    # This includes two tasks:
    # 1. Reconciling eligibilities if needed, where reconciliation is the process by which
    #    applicant eligibilities are adjusted to align with the current enrollment status.
    # 2. Rebuilding the family determination.
    #
    # @param params [Hash] Parameters containing enrollment information
    # @option params [String] :gid GlobalID of the enrollment to process
    #
    # @return [Dry::Monads::Success<Hash>, Dry::Monads::Failure<String>]
    #   Success with results hash or Failure with error message
    #
    # @see Operations::HbxEnrollments::EligibilityReconciliation::ReconcileEligibilitiesWithEnrollment
    # @see Operations::Eligibilities::BuildFamilyDetermination
    class OnSave
      include Dry::Monads[:do, :result]

      RECONCILIATION_STATUSES = HbxEnrollment::ENROLLED_AND_RENEWAL_STATUSES.freeze

      def call(params)
        yield validate(params)
        reconciliation_result = yield reconcile_if_needed
        _determination = yield build_family_determination

        Success({enrollment: @enrollment, reconciliation_result: reconciliation_result})
      end

      private

      # Validates parameters and sets the enrollment as an instance variable
      #
      # @param params [Hash] Input parameters containing enrollment GID
      # @option params [String] :gid GlobalID of the enrollment
      #
      # @return [Dry::Monads::Success<HbxEnrollment>, Dry::Monads::Failure<String>]
      #   Success with enrollment or Failure with error message
      def validate(params)
        return Failure('Missing enrollment GID') unless params[:gid].present?

        @enrollment = GlobalID::Locator.locate(params[:gid])
        return Failure('Enrollment not found') unless @enrollment

        Success(@enrollment)
      rescue StandardError => e
        Failure("Failed to fetch enrollment: #{e.message}")
      end

      # Attempts to reconcile new enrollment state with eligibilities
      #
      # First checks if the enrollment qualifies for reconciliation, then performs reconciliation if needed.
      #
      # @return [Dry::Monads::Success<Hash>, Dry::Monads::Failure<String>]
      #   Success with result hash containing status, application, and message or Failure for any reconciliation errors
      def reconcile_if_needed
        reconciliation_needed, skip_reason = enrollment_requires_reconciliation?

        return Success({status: :skipped, application: nil, message: skip_reason}) unless reconciliation_needed

        reconcile_operation = Operations::HbxEnrollments::EligibilityReconciliation::ReconcileEligibilitiesWithEnrollment.new
        result = reconcile_operation.call(enrollment: @enrollment)

        if result.success?
          Success({status: :success, application: result.value!, message: 'Reconciliation completed successfully'})
        else
          Failure("Reconciliation failed: #{result.failure}")
        end
      rescue StandardError => e
        Failure("Reconciliation error: #{e.message}")
      end

      # Builds family determination for the enrollment's family
      #
      # @return [Dry::Monads::Success<Eligibilities::Determination>, Dry::Monads::Failure<String>]
      #   Success with determination or Failure with error message
      def build_family_determination
        family = @enrollment.family
        return Failure('Family not found for enrollment') unless family

        result = Operations::Eligibilities::BuildFamilyDetermination.new.call(family: family)

        if result.success?
          Success(result.value!)
        else
          Failure("Family determination failed: #{result.failure}")
        end
      rescue StandardError => e
        Failure("Failed to build family determination: #{e.message}")
      end

      # Checks if enrollment requires reconciliation based on its state and generation reason
      #
      # Only handle enrollments transitioning to active states (enrolled, renewing, etc.),
      # and suppress processing for enrollments generated by application determinations.
      #
      # @note determination-generated enrollments don't require eligibility reconciliation; hub calls already process eligibilities.
      #
      # @return [Array(Boolean, String?)] Tuple indicating if reconciliation is needed and an optional reason
      def enrollment_requires_reconciliation?
        return [false, invalid_state_message] unless valid_enrollment_state?
        return [false, 'Enrollments generated by application determinations do not require reconciliation'] if enrollment_change_from_determination?

        [true, nil]
      end

      # Checks if enrollment is in a valid state for evidence updates
      #
      # Valid states are those where the member is actively enrolled or renewing,
      # as defined by {HbxEnrollment::ENROLLED_AND_RENEWAL_STATUSES}.
      #
      # @return [Boolean] True if enrollment state allows evidence updates
      def valid_enrollment_state?
        RECONCILIATION_STATUSES.include?(@enrollment.aasm_state)
      end

      # Generates error message for invalid enrollment states
      def invalid_state_message
        valid_states = RECONCILIATION_STATUSES.join(', ')
        "Enrollment must be in one of these states: #{valid_states}"
      end

      # Checks if this enrollment change event is the result of application determination creating
      # and transitioning the enrollment to coverage_selected state.
      def enrollment_change_from_determination?
        @enrollment.coverage_selected? && @enrollment.generation_reason == :application_determination
      end
    end
  end
end
